services:
  transmission-telegram-bot:
    image: ghcr.io/vovcharaa/transmission-telegram-bot:latest
    container_name: transmission-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
