services:
  transmission:
    image: lscr.io/linuxserver/transmission:4.0.6
    restart: unless-stopped
    ports:
      - "9091:9091"  # web interface
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - TZ=Asia/Nicosia
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - ./volume/media:/downloads
